# Generated by Django 5.1.1 on 2024-10-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
